# ------------------------------------
# Stage 1: Build the Angular Application
# ------------------------------------
FROM node:22-alpine as build

# Set the working directory
WORKDIR /app

# Copy dependency graphs
COPY package.json package-lock.json ./

# Install packages (using legacy-peer-deps to ignore @angular/fire version mismatch with Angular 19/21+)
RUN npm ci --legacy-peer-deps

# Copy the rest of the application
COPY . .

# Build the Angular application for production
RUN npm run build

# ------------------------------------
# Stage 2: Serve via Nginx
# ------------------------------------
FROM nginx:alpine

# Copy the generated custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy compiled build artifacts from Stage 1 into Nginx public directory
# Note: Ensure the dist path matches the output path generated by angular.json
COPY --from=build /app/dist/finlit-lab/browser /usr/share/nginx/html

# Expose port (Cloud Run automatically expects mapped ports, usually 8080 or respects Dockerfile EXPOSE)
EXPOSE 80

# Start Nginx automatically
CMD ["nginx", "-g", "daemon off;"]
